[build]
  publish = "build"
  command = "DISABLE_ESLINT_PLUGIN=true npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# Production environment variables
[context.production.environment]
  NODE_ENV = "production"
  REACT_APP_NAME = "Coffee Meeting Platform"
  REACT_APP_VERSION = "2.0.0"
  REACT_APP_ENVIRONMENT = "production"
  REACT_APP_DEBUG = "false"
  # NOTE: Set REACT_APP_API_URL in Netlify environment variables
  # REACT_APP_API_URL = "https://your-production-api.com"
  REACT_APP_API_TIMEOUT = "30000"
  REACT_APP_ENABLE_NOTIFICATIONS = "true"
  REACT_APP_ENABLE_REALTIME_UPDATES = "true"
  REACT_APP_ENABLE_FILE_UPLOAD = "true"
  REACT_APP_ENABLE_BULK_OPERATIONS = "true"

# Branch deploy (staging)
[context.branch-deploy.environment]
  NODE_ENV = "development"
  REACT_APP_DEBUG = "true"

# Deploy preview
[context.deploy-preview.environment]
  NODE_ENV = "development"
  REACT_APP_DEBUG = "true"

# Headers pour sécurité
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
